export const mockJobs = [
  {
    id: 1,
    title: 'Senior AI Engineer',
    company: 'TechCorp AI',
    location: 'San Francisco, CA',
    salary: '$180k - $240k',
    type: 'Full-time',
    matchScore: 95,
    description: 'Lead AI model development and deployment for enterprise solutions.',
    skills: ['Python', 'TensorFlow', 'PyTorch', 'MLOps'],
    posted: '2 days ago',
  },
  {
    id: 2,
    title: 'Machine Learning Scientist',
    company: 'DataMinds Inc',
    location: 'Remote',
    salary: '$160k - $200k',
    type: 'Full-time',
    matchScore: 92,
    description: 'Research and develop cutting-edge ML algorithms for predictive analytics.',
    skills: ['Python', 'Scikit-learn', 'Deep Learning', 'Statistics'],
    posted: '1 week ago',
  },
  {
    id: 3,
    title: 'Full Stack Developer',
    company: 'WebSolutions Co',
    location: 'New York, NY',
    salary: '$140k - $180k',
    type: 'Full-time',
    matchScore: 88,
    description: 'Build scalable web applications with modern tech stack.',
    skills: ['React', 'Node.js', 'TypeScript', 'AWS'],
    posted: '3 days ago',
  },
  {
    id: 4,
    title: 'Data Scientist',
    company: 'Analytics Pro',
    location: 'Boston, MA',
    salary: '$130k - $170k',
    type: 'Full-time',
    matchScore: 85,
    description: 'Extract insights from complex datasets and build predictive models.',
    skills: ['Python', 'SQL', 'Tableau', 'Statistical Analysis'],
    posted: '5 days ago',
  },
  {
    id: 5,
    title: 'DevOps Engineer',
    company: 'CloudFirst',
    location: 'Seattle, WA',
    salary: '$150k - $190k',
    type: 'Full-time',
    matchScore: 78,
    description: 'Manage cloud infrastructure and CI/CD pipelines.',
    skills: ['Kubernetes', 'Docker', 'AWS', 'Terraform'],
    posted: '1 day ago',
  },
  {
    id: 6,
    title: 'Frontend Architect',
    company: 'DesignTech',
    location: 'Austin, TX',
    salary: '$170k - $210k',
    type: 'Full-time',
    matchScore: 82,
    description: 'Lead frontend architecture and mentor development team.',
    skills: ['React', 'Vue', 'TypeScript', 'Architecture'],
    posted: '4 days ago',
  },
  {
    id: 7,
    title: 'AI Research Scientist',
    company: 'FutureLabs',
    location: 'Remote',
    salary: '$200k - $280k',
    type: 'Full-time',
    matchScore: 90,
    description: 'Conduct cutting-edge research in natural language processing.',
    skills: ['Python', 'NLP', 'Transformers', 'Research'],
    posted: '1 week ago',
  },
  {
    id: 8,
    title: 'Backend Engineer',
    company: 'ServerPro',
    location: 'Chicago, IL',
    salary: '$135k - $175k',
    type: 'Full-time',
    matchScore: 75,
    description: 'Design and implement robust backend systems and APIs.',
    skills: ['Node.js', 'PostgreSQL', 'GraphQL', 'Microservices'],
    posted: '6 days ago',
  },
  {
    id: 9,
    title: 'ML Platform Engineer',
    company: 'AI Systems',
    location: 'San Jose, CA',
    salary: '$165k - $205k',
    type: 'Full-time',
    matchScore: 87,
    description: 'Build and maintain ML infrastructure and deployment pipelines.',
    skills: ['Python', 'Kubernetes', 'MLflow', 'AWS'],
    posted: '2 days ago',
  },
  {
    id: 10,
    title: 'Product Engineer',
    company: 'StartupXYZ',
    location: 'Los Angeles, CA',
    salary: '$145k - $185k',
    type: 'Full-time',
    matchScore: 68,
    description: 'Ship high-quality products from concept to launch.',
    skills: ['React', 'Python', 'Product Design', 'Agile'],
    posted: '3 days ago',
  },
];

export const mockSkills = {
  strengths: [
    { name: 'Python', level: 95, category: 'Programming' },
    { name: 'Machine Learning', level: 90, category: 'AI/ML' },
    { name: 'React', level: 85, category: 'Frontend' },
    { name: 'Data Analysis', level: 88, category: 'Analytics' },
    { name: 'Problem Solving', level: 92, category: 'Soft Skills' },
  ],
  gaps: [
    { name: 'Kubernetes', current: 45, target: 80, priority: 'High' },
    { name: 'System Design', current: 60, target: 85, priority: 'High' },
    { name: 'GraphQL', current: 35, target: 75, priority: 'Medium' },
    { name: 'TypeScript', current: 55, target: 85, priority: 'Medium' },
    { name: 'Public Speaking', current: 40, target: 70, priority: 'Low' },
  ],
  radarData: [
    { skill: 'Technical', value: 90 },
    { skill: 'Leadership', value: 65 },
    { skill: 'Communication', value: 75 },
    { skill: 'Problem Solving', value: 92 },
    { skill: 'Creativity', value: 80 },
    { skill: 'Teamwork', value: 85 },
  ],
};

export const mockMessages = [
  {
    id: 1,
    role: 'assistant',
    content: 'Hello! I\'m your AI career assistant. How can I help you today?',
    timestamp: new Date(Date.now() - 300000),
  },
  {
    id: 2,
    role: 'user',
    content: 'What skills should I focus on to improve my job prospects?',
    timestamp: new Date(Date.now() - 240000),
  },
  {
    id: 3,
    role: 'assistant',
    content: 'Based on your profile, I recommend focusing on:\n\n1. **Kubernetes** - High demand in DevOps roles\n2. **System Design** - Essential for senior positions\n3. **TypeScript** - Increasingly popular in modern web development\n\nWould you like specific learning resources for any of these?',
    timestamp: new Date(Date.now() - 180000),
  },
];
